server.port=8080
spring.application.name=order-service

# Point to the local sidecar proxy running inside the same pod
spring.kafka.bootstrap-servers=127.0.0.1:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Enable Java 21 Virtual Threads
spring.threads.virtual.enabled=true